Update nextjs.yml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -78,20 +78,20 @@ jobs:
         run: ${{ steps.detect-package-manager.outputs.runner }} next build
       # - name: Static HTML export with Next.js
       #   run: ${{ steps.detect-package-manager.outputs.runner }} next export
-      - name: Move Output Directory
-        run: |
-          mkdir tmp-dir
-          if [ -d "out" ]; then
-            mv out tmp-dir/
-            mv tmp-dir out
-          else
-           echo "Directory 'out' not found. Make sure 'next export' ran successfully."
-           exit 1
-          fi
-      - name: Upload artifact
-        uses: actions/upload-pages-artifact@v2
-        with:
-          path: ./out
+      #- name: Move Output Directory
+      #  run: |
+      #    mkdir tmp-dir
+      #    if [ -d "out" ]; then
+      #      mv out tmp-dir/
+      #      mv tmp-dir out
+      #    else
+      #     echo "Directory 'out' not found. Make sure 'next export' ran successfully."
+      #     exit 1
+      #    fi
+      #- name: Upload artifact
+      #  uses: actions/upload-pages-artifact@v2
+      #  with:
+      #    path: ./out
 
   # Deployment job
   deploy:
